### ISSUE TITLE
Уникальность имен превью картинок

### ISSUE THREAD

**Issue by radist** [oc-shopaholic/oc-toolbox-plugin#101]
https://github.com/oc-shopaholic/oc-toolbox-plugin/blob/master/classes/item/MainItem.php#L253

При создании объекта File не создается id , что при некотором стечении обстоятельство может привести к смешиванию картинок превью. Т.к. id используется для уникализации имени. 

Как вариант решения 

```php
$obFile = File::make($arFileData);
$obFile->disk_name = array_get($arFileData, 'disk_name');
$obFile->id = array_get($arFileData, 'id');
```

**Comment by kharanenka** [comment]
Fixed in version 1.33.1
