### ISSUE TITLE
Class "RainLab\Translate\Models\Locale" not found" 

### ISSUE THREAD

**Issue by baberuth22** [oc-shopaholic/oc-toolbox-plugin#122]
I'm running October 3 and I get this error when trying to create my first product with Shopaholic.

Class "RainLab\Translate\Models\Locale" not found" on line 33 of /plugins/lovata/toolbox/traits/helpers/TraitInitActiveLang.php

**Comment by kharanenka** [comment]
Fixed in version 1.34.4
