### ISSUE TITLE
When using AbstractImportModelFromCSV, images cannot be uploaded to S3 storage

### ISSUE THREAD

**Issue by kornep** [oc-shopaholic/oc-toolbox-plugin#123]
I migrated my project to an S3 storage, and when I try to import models using CSV Import (e.g., shopaholic category) but images are not uploaded.
After some digging, I found out that the problem seems to be in the AbstractImportModelFromCSV helper's initPreviewImage() method on these lines of code:

```
        $this->sPreviewImage = storage_path($this->sPreviewImage);
        if (!file_exists($this->sPreviewImage)) {
            $this->sPreviewImage = null;
        }
```

Using storage_path() function it will do a file exist on local storage, when it should check if file exists on S3 storage. 
Will there be an update to support uploading images through the AbstractImportModelFromCSV helper to S3 storage, or is there an alternative solution?

**Comment by kornep** [comment]
Couldn't find a good solution yet. I will get back if I do find one.

**Comment by kornep** [comment]
Hi ! Any news for a merge on the pull request ?

**Comment by kharanenka** [comment]
PR merged. Fix available in 2.0.0 plugin version. Thanks for your contribution

**Comment by kornep** [comment]
Thanks for the merge !

**Comment by kornep** [comment]
@kharanenka - I needed this update on ^1.0 version for projects that are not update to october version 3.

**Comment by kharanenka** [comment]
You should remove manually changes from [PR](https://github.com/oc-shopaholic/oc-toolbox-plugin/pull/125) for your project. We can't support v1 with this changes, because v1 doesn't have interfaces. You should freeze updates for Toolbox plugin.

**Comment by kornep** [comment]
ok, that's what I'll do. Thanks !
