### ISSUE TITLE
Make data returned from EVENT_BEFORE_IMPORT available to functions like initPreviewImage

### ISSUE THREAD

**Issue by SebastiaanKloos** [oc-shopaholic/oc-toolbox-plugin#92]
If you return a custom array via EVENT_BEFORE_IMPORT, this data is not available in functions called by prepareImportData. This is because the event is fired only after prepareImportData.

For example, to ensure that you can edit the preview_image attribute during the import, it is necessary to fire the event before calling the prepareImportData function.

Pull request for this issue:
https://github.com/oc-shopaholic/oc-toolbox-plugin/pull/91

**Comment by SebastiaanKloos** [comment]
@kharanenka Or should a new event be better in this situation?

**Comment by kharanenka** [comment]
Hi @SebastiaanKloos ! What changes are you talking about? Can you give some example with "preview_image" field?

**Comment by SebastiaanKloos** [comment]
@kharanenka hi! Yes you can see my plugins repo https://github.com/kloos-dev/oc-importshopaholic as example of what I would like to do with the preview_image

**Comment by kharanenka** [comment]
I think that file uploads should be implemented in main plugin. It makes no sense to move this into separate plugin. We are planning to make this feature in main plugin.

**Comment by kharanenka** [comment]
We will be glad if you make PR with implementation of this feature.

**Comment by SebastiaanKloos** [comment]
> We will be glad if you make PR with implementation of this feature.

No problem at all. I can make a pr ready by tomorrow. The reason why I created a new plugin was that I needed the functionality last week😬

**Comment by kharanenka** [comment]
It is good news! Thanks

**Comment by SebastiaanKloos** [comment]
Created a pr https://github.com/oc-shopaholic/oc-toolbox-plugin/pull/94

**Comment by vshepel** [comment]
> We will be glad if you make PR with implementation of this feature.

How much more to wait before the implementation of this pr? We really need a similar functionality!
